NumPy stands for numericla python

In [1]:
pip install numpy

In [2]:
import numpy as np

mathematical operation

In [3]:
np.sqrt(25)

5.0

In [4]:
np.power(5,2)

25

In [5]:
np.round(10.5469)

11.0

In [6]:
np.sin(1.57)

0.9999996829318346

In [7]:
np.log(100)#base is 'e' not 10

4.605170185988092

# **Arrays and their Operations**

In [13]:
import numpy as np
#creating a 1D array
arr1=np.array([1,2,3,4])
print(arr1)

arr2=np.array([5,6,7,8])
print(arr2)



[1 2 3 4]
[5 6 7 8]


In [10]:
#creating a 2D array
arr3=np.array([[1,2,3],[4,5,6]])
print(arr3)

[[1 2 3]
 [4 5 6]]


In [11]:
#creating a 3D array
arr4=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr4)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


Array operations:NumPy allows element-wise operations and broadcasting

In [15]:
#elemnt-wise addition
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
arr3=arr1+arr2
print(arr3)


[ 6  8 10 12]


In [16]:
#lement-wise multification

arr3=arr1*arr2
print(arr3)

[ 5 12 21 32]


Basic Array methods

In [19]:
#array shape
shape=arr1.shape #two rows and three columns
print(arr1.shape)
print(shape)

(4,)
(4,)


In [20]:
a=np.array([1,2,3,4,5,6,7,8,9])

In [21]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
b=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3) #reshaping teh 1D array to 2D array
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
#number od dimentions
dim =b.ndim
print(dim)

2


In [32]:
#total numbers of elemnts
size=b.size
print(size)
print(b.size)

9
9


In [33]:
b[1,2] #accesing a value in 2D array

6

In [34]:
b[1:3,1:3] #rows 1to 3 & columns 1to3

array([[5, 6],
       [8, 9]])

In [35]:
b[2,:] #get the values of the row

array([7, 8, 9])

In [36]:
b[:,2] #get the values of the column

array([3, 6, 9])

In [37]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(a)

[1 2 3 4 5 6 7 8 9]


In [38]:
a.sum() #sum of all elements


45