# Working with imbanace data

In [191]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')

In [192]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [193]:
data=pd.DataFrame(pd.read_csv('/content/drive/MyDrive/ML/Datasets/Bank.csv'))

In [194]:
data.head()

age  duration  emp_var_rate  cons_price_idx  cons_conf_idx  euribor3m  \
0   44       210           1.4          93.444          -36.1      4.963   
1   53       138          -0.1          93.200          -42.0      4.021   
2   28       339          -1.7          94.055          -39.8      0.729   
3   39       185          -1.8          93.075          -47.1      1.405   
4   55       137          -2.9          92.201          -31.4      0.869   

   nr_employed  y  
0       5228.1  0  
1       5195.8  0  
2       4991.6  1  
3       5099.1  0  
4       5076.2  1

In [195]:
#allocate x and y using iloc
x=data.iloc[:,:7]
y=data.iloc[:,7]


In [196]:
x.shape

(41188, 7)

In [197]:
y.value_counts()

y
0    36548
1     4640
Name: count, dtype: int64

In [198]:
from imblearn.over_sampling import SMOTE,ADASYN

In [199]:
smt=SMOTE()#1st method using smote

In [200]:
x1,y1=smt.fit_resample(x,y)

In [201]:
y1.value_counts()

y
0    36548
1    36548
Name: count, dtype: int64

In [202]:
x.shape

(41188, 7)

In [203]:
ada = ADASYN() #2nd method using ASASYN

In [204]:
x2,y2=ada.fit_resample(x,y)

In [205]:
y2.value_counts()

y
1    37352
0    36548
Name: count, dtype: int64

In [206]:
x1_train, x1_test, y1_train, y1_test = train_test_split(x1, y1, test_size=0.2, random_state=100)




In [207]:
len(x1_train)



58476

In [208]:
#evaluate tge model
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report


In [209]:
# train the model
model1 = LogisticRegression()
model1.fit(x1_train, y1_train)

LogisticRegression()

In [210]:
model1.intercept_
model1.coef_

array([[-0.00402787,  0.00650684, -0.33362078,  0.40993142,  0.04580014,
        -0.30284721, -0.00739099]])

In [211]:
y1_pred = model1.predict(x1_test)
y1_pred

array([1, 0, 1, ..., 0, 1, 0])

In [212]:
y1_pred_prob = model1.predict_proba(x1_test)
# probability value prediction for 0 and 1
# If it is more than 0.5 we can decide whether it is 0 or 1
# Here the positive class has been taken as 0
y1_pred_prob

array([[0.02828073, 0.97171927],
       [0.54309551, 0.45690449],
       [0.00338576, 0.99661424],
       ...,
       [0.89356432, 0.10643568],
       [0.11961377, 0.88038623],
       [0.93896771, 0.06103229]])

In [213]:
y1_pred_prob = model1.predict_proba(x1_test)[:, 1]
# getting predicted probability values of class 1 as a 1D array
y1_pred_prob

array([0.97171927, 0.45690449, 0.99661424, ..., 0.10643568, 0.88038623,
       0.06103229])

In [214]:
confusion_matrix(y1_test, y1_pred)

array([[6064, 1199],
       [1098, 6259]])

In [215]:
accuracy_score(y_test, y_pred)

0.8454172366621067

In [216]:
print('use ADASYN',classification_report(y_test, y_pred))

use ADASYN               precision    recall  f1-score   support

           0       0.85      0.83      0.84      7263
           1       0.84      0.86      0.85      7357

    accuracy                           0.85     14620
   macro avg       0.85      0.85      0.85     14620
weighted avg       0.85      0.85      0.85     14620



In [217]:
x2_train, x2_test, y2_train, y2_test = train_test_split(x2, y2, test_size=0.2, random_state=100)

In [218]:
model2 = LogisticRegression()
model2.fit(x2_train, y2_train)

LogisticRegression()

In [219]:
model2.intercept_
model2.coef_

array([[-0.00224775,  0.00614884, -1.28651863,  0.67999199, -0.00324623,
         0.74843487, -0.01333523]])

In [220]:
y2_pred = model2.predict(x2_test)
y2_pred

array([1, 0, 1, ..., 1, 1, 1])

In [221]:
y2_pred_prob = model2.predict_proba(x2_test)

y2_pred_prob

array([[1.31791725e-01, 8.68208275e-01],
       [7.10045257e-01, 2.89954743e-01],
       [3.55207987e-01, 6.44792013e-01],
       ...,
       [3.54026393e-04, 9.99645974e-01],
       [9.97931707e-02, 9.00206829e-01],
       [2.68928636e-01, 7.31071364e-01]])

In [222]:
y2_pred_prob = model2.predict_proba(x2_test)[:, 1]
# getting predicted probability values of class 1 as a 1D array
y2_pred_prob

array([0.86820827, 0.28995474, 0.64479201, ..., 0.99964597, 0.90020683,
       0.73107136])

In [223]:
confusion_matrix(y2_test, y2_pred)

array([[5859, 1392],
       [1316, 6213]])

In [224]:
accuracy_score(y2_test, y2_pred)

0.8167794316644114

In [225]:
print('use ADASYN',classification_report(y2_test, y2_pred))

use ADASYN               precision    recall  f1-score   support

           0       0.82      0.81      0.81      7251
           1       0.82      0.83      0.82      7529

    accuracy                           0.82     14780
   macro avg       0.82      0.82      0.82     14780
weighted avg       0.82      0.82      0.82     14780

