In [1]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score

In [ ]:
advertising = pd.DataFrame(pd.read_csv('advertising for LR.csv'))

In [ ]:
x = advertising.iloc[:, :3]
y = advertising.iloc[:, 3]

In [ ]:
model = LinearRegression()

In [ ]:
cvals = cross_val_score(model, x, y, cv=5)

In [ ]:
cvals

array([0.87556263, 0.93177791, 0.92150403, 0.84554586, 0.90247132])

In [ ]:
np.mean(cvals)

0.8953723525274103

In [ ]:
cvals = cross_val_score(model, x, y, cv=5, scoring='neg_mean_squared_error')

In [ ]:
cvals

array([-3.05606897, -2.02676065, -1.85105212, -4.72039259, -2.63694072])

In [ ]:
cvals = -cross_val_score(model, x, y, cv=5, scoring='neg_mean_squared_error')

In [ ]:
cvals

array([3.05606897, 2.02676065, 1.85105212, 4.72039259, 2.63694072])

In [ ]:
RMSE = np.sqrt(cvals)

In [ ]:
RMSE

array([1.7481616 , 1.42364344, 1.36053376, 2.17264645, 1.62386598])

In [ ]:
np.mean(RMSE)

1.6657702460059216

In [ ]:
model = LinearRegression()

In [ ]:
model.fit(x, y)

LinearRegression()

In [ ]:
model.intercept_

4.625124078808653

In [ ]:
model.coef_

array([0.05444578, 0.10700123, 0.00033566])

In [ ]:
y_pred = model.predict(x)

In [ ]:
print(y)

0      22.1
1      10.4
2      12.0
3      16.5
4      17.9
       ... 
195     7.6
196    14.0
197    14.8
198    25.5
199    18.4
Name: Sales, Length: 200, dtype: float64
