NumPy stands for Numerical Python. It's powerful library for numerical computing in python.  

In [ ]:
pip install numpy

In [ ]:
import numpy as np

Mathematical Operations

In [ ]:
np.sqrt(36)

6.0

In [ ]:
np.power(5, 3)

125

In [ ]:
np.round(10.6904)

11.0

In [ ]:
np.sin(1.57)

0.9999996829318346

In [ ]:
np.log(100)

4.605170185988092

# Arrays and Their Operations

In [ ]:
import numpy as np
# Creating 1D array

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

arr5 = np.array([1, 2, 3, 4])
print(arr5)

[1 2 3 4 5]
[1 2 3 4]


In [ ]:
# Creating 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]]) # you have to use two square brackets
print(arr2)

[[1 2 3]
 [4 5 6]]


Array Operations: NumPy allows element-wise operations and broadcasting

In [ ]:
# Element-wise addition
arr3 = arr1 + arr1
print(arr3)

[ 2  4  6  8 10]


In [ ]:
# Element-wise multiplication
arr4 = arr1 * arr1
print(arr4)

[ 1  4  9 16 25]


In [ ]:
arr7 = arr1 * arr5
print(arr7)

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

Basic Array Methods

In [ ]:
# Array Shape
shape = arr2.shape #two rows and three columns
print(arr2.shape)

print(shape)

(2, 3)
(2, 3)


In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9])

In [ ]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b = np.array([1,2,3,4,5,6,7,8,9]).reshape(3, 3) #reshaping the 1D array into a 2D array
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Number of dimention
dim = b.size
print(dim)

9


In [ ]:
# Total number of elements
size = b.size
print(size)

print(b.size)

9
9


In [ ]:
b[1,2] #accessing a value in a 2D array

6

In [ ]:
b[1:3, 1:3] #rows 1to3 & columns 1to3

array([[5, 6],
       [8, 9]])

In [ ]:
b[2,:] #get a value of the row

array([7, 8, 9])

In [ ]:
b[:,2] #get a value of the column

array([3, 6, 9])

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a)

[1 2 3 4 5 6 7 8 9]


In [ ]:
a.sum() #sum of all the elements

45

In [ ]:
a.mean()

5.0

In [ ]:
a.max()

9